# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
micro_state_c_step <- function(micro_state, parms, control, time) {
    .Call('spore_micro_state_c_step', PACKAGE = 'spore', micro_state, parms, control, time)
}

#' @export
micro_state_c_stepto <- function(micro_state, parms, control, time, timeto, record = 0L, run = 1L) {
    .Call('spore_micro_state_c_stepto', PACKAGE = 'spore', micro_state, parms, control, time, timeto, record, run)
}

tabulate1 <- function(x, max) {
    .Call('spore_tabulate1', PACKAGE = 'spore', x, max)
}

#' @export
lift_macro_state <- function(macro_state, parms) {
    .Call('spore_lift_macro_state', PACKAGE = 'spore', macro_state, parms)
}

